"""update refresh_tokens table

Revision ID: 3020428791a1
Revises: e3519d80ff69
Create Date: 2026-02-07 19:32:49.756029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3020428791a1'
down_revision: Union[str, Sequence[str], None] = 'e3519d80ff69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('revoked', sa.Boolean(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('expires_at', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'expires_at')
    op.drop_column('refresh_tokens', 'revoked')
    # ### end Alembic commands ###
