"""changed brand_id datatype

Revision ID: 5758bd9b5ca4
Revises: c116df3581a8
Create Date: 2025-09-20 03:53:35.235015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5758bd9b5ca4'
down_revision: Union[str, Sequence[str], None] = 'c116df3581a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "brand_id",
        existing_type=postgresql.UUID(as_uuid=True),
        type_=sa.String(),
        existing_nullable=False,
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "brand_id",
        existing_type=sa.String(),
        type_=sa.dialects.postgresql.UUID(as_uuid=True),
        existing_nullable=True,
        nullable=False,
    )
    # ### end Alembic commands ###
