"""added address table

Revision ID: 5cf7c181b657
Revises: e3e10dadb8c6
Create Date: 2025-11-17 21:57:16.506079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cf7c181b657'
down_revision: Union[str, Sequence[str], None] = 'e3e10dadb8c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'address',
        sa.Column('address_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('address_type', sa.Enum('home', 'office', 'other', name='addresstype'), nullable=False),
        sa.Column('receiver_name', sa.String(length=100)),
        sa.Column('receiver_email', sa.String(length=320), nullable=False),
        sa.Column('receiver_contact', sa.String(length=10), nullable=False),
        sa.Column('address_line_1', sa.String(length=200), nullable=False),
        sa.Column('address_line_2', sa.String(length=200)),
        sa.Column('landmark', sa.String(length=100)),
        sa.Column('city', sa.String(length=100), nullable=False),
        sa.Column('state', sa.String(length=100), nullable=False),
        sa.Column('pincode', sa.String(length=50), nullable=False),
        sa.Column('country', sa.String(length=100), nullable=False),
        sa.Column('is_default', sa.Boolean(), nullable=False, server_default="false"),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id']),
        sa.PrimaryKeyConstraint('address_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    # ### end Alembic commands ###
