"""'test'

Revision ID: b380573b03c2
Revises: 5cf7c181b657
Create Date: 2025-11-17 23:45:52.736057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b380573b03c2'
down_revision: Union[str, Sequence[str], None] = '5cf7c181b657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    category_enum = sa.Enum('Men', 'Women', 'Kids', name='ategory')
    category_enum.create(op.get_bind(), checkfirst=True)
    op.execute(
        "ALTER TABLE products "
        "ALTER COLUMN category TYPE category "
        "USING category::category"
    )
    op.create_unique_constraint(None, 'address', ['address_id'])
    op.alter_column('products', 'brand_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('Men', 'Women', 'Kids', name='category'),
               existing_nullable=False)
    op.create_unique_constraint(None, 'products', ['product_id'])
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['brand_id'])
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='unique')
    op.alter_column('products', 'category',
               existing_type=sa.Enum('Men', 'Women', 'Kids', name='category'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('products', 'brand_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'address', type_='unique')
    op.execute(
        "ALTER TABLE products "
        "ALTER COLUMN category TYPE VARCHAR(100) "
        "USING category::text"
    )

    # 2. Drop ENUM
    category_enum = sa.Enum(name='category')
    category_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
