"""update refresh_tokens table

Revision ID: e3519d80ff69
Revises: f888a5911576
Create Date: 2026-02-07 17:38:37.800376

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3519d80ff69"
down_revision: Union[str, Sequence[str], None] = "f888a5911576"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "refresh_tokens", ["token"])
    op.create_foreign_key(None, "refresh_tokens", "users", ["user_id"], ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "refresh_tokens", type_="foreignkey")
    op.drop_constraint(None, "refresh_tokens", type_="unique")
    # ### end Alembic commands ###
