"""added user model and schema

Revision ID: e3e10dadb8c6
Revises: 5758bd9b5ca4
Create Date: 2025-09-25 23:28:33.533456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3e10dadb8c6'
down_revision: Union[str, Sequence[str], None] = '5758bd9b5ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column("user_id", sa.UUID(as_uuid=True), primary_key=True, autoincrement=False, nullable=False),
        sa.Column("user_email", sa.VARCHAR(length=320), unique=True, nullable=False),
        sa.Column("user_contact", sa.VARCHAR(length=10), nullable=False),
        sa.Column("password", sa.VARCHAR, nullable=False),
        sa.Column("role", sa.Enum("admin", "seller", "customer", name="userroles"), nullable=False, server_default="customer"),

        sa.Column("user_created_time", sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column("user_updated_time", sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column("user_last_login_time", sa.TIMESTAMP, nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
