"""added refresh token table

Revision ID: f888a5911576
Revises: 0d773e370669
Create Date: 2026-02-02 11:09:42.016063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f888a5911576'
down_revision: Union[str, Sequence[str], None] = '0d773e370669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('token'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.UniqueConstraint('token')
    )
    op.alter_column('products', 'category',
               existing_type=postgresql.ENUM('Men', 'Women', 'Kids', name='category'),
               nullable=True)
    op.alter_column('products', 'product_image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'product_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'category',
               existing_type=postgresql.ENUM('Men', 'Women', 'Kids', name='category'),
               nullable=False)
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
