"""Created a new table for Brands

Revision ID: ffa30471b208
Revises: 3593cb4049ed
Create Date: 2025-09-15 01:56:56.758145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffa30471b208'
down_revision: Union[str, Sequence[str], None] = '3593cb4049ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
        sa.Column('brand_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('brand_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('brand_id', name=op.f('brands_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brands')
    # ### end Alembic commands ###
